### ISSUE TITLE
Proposed roadmap to stable 4.0 version

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/ecommerce#610]
# Proposed roadmap to stable 4.0 version

### Fix it in 3.x before working on 4.x:

- [x] #601 - add product to cart - Call to a member function getManager() on null
- [x] #605 - show catalog - Variable "macros" does not exist 
- [x] #625 - Inject basketfactory for payment controller
- [x] #630 - missing method CustomerController:getCurrentRequest 
- [x] ~~#627 - Added missing profile part by add ProfileBundle~~ 
#634 - Add profile to CustomerBundle
- [x] ~~#618 fix ProductBundle:CollectionController~~
#631 - Fix navigation product's collection

### TODO before release 4.x
- [ ] release sandbox 3.x
- [ ] add support for Symfony 5.x (and drop for Symfony < 3.4)
- [ ] inject service - aviod using container for better testing 
- [ ] public service should have only get methods, to set something injection will be required -to discuse
- [ ] make code more readable 
    - [ ] split BasketController to BasketController and BasketOrderStepsController
    - [ ] more
- [ ] update tests
- [ ] remove SonataUserBundle dependencies and add this bundle to sugest
- [ ] remove SonataSeoBundle dependencies and add this bundle to sugest
- [ ] create symfony flex recipe

### optionally add some feature
- [ ] return merchandise authorization
- [ ] product warranty period list
- [ ] discount module 

### and like for each library:
- reconfigure Travis on the master branch via dev-kit
- merge the stable branch in master one last time
- drop old versions of php
- drop old versions of symfony
- optionally drop old versions of dependencies
- cleanup NEXT_MAJOR: and deprecated things
- create a $nextMajor.x from master
- alias master to $nextMajor + 1
- for non-leaf libraries, explain the 3-branch system in CONTRIBUTING.md

**Comment by wbloszyk** [comment]
In this week i want to PR stable ecommerce 3.0. (and stable sandbox 3.0 with unit and behat tests).

I have <10 errors to fix.

@salamichel :
Do you have issue with payment? I got timeout from CURL :(
BTW, thanks for your #603 and fix #601

**Comment by greg0ire** [comment]
I think you should ping recent contributors (@quisse and @jeroendk, for instance) regarding the roadmap and your PRs, you will get better feedback. The only people who see this are the Sonata team, and we are mostly maintainers, I'm not even sure someone in the team actually uses this package.

**Comment by salamichel** [comment]
@wbloszyk hi i didn t proceed any payment yet. Not enought time. Thx in advance for your contribution

**Comment by wbloszyk** [comment]
They are pinging now., thanks (also @salamichel). In my company we have shop (in pure PHP5.3 and mysql/mssql). I dont wanna develop it. Better for me is develop this project (as open source) and make some modifications (commercial use). For now i want develop it in 3 steps:
1. Release stable ecommerce and sandbox for symfony 3.4
1. Upgrade sandbox to 4.4 (LTS version)
1. Add doctrine interface mapping for ecommerce (this should allow use tables from other shop)

**Comment by jeroendk** [comment]
@wbloszyk What are your current issues and with what do you need help? I'm glad to help out as I am waiting for a stable 3.0 release for a while now.

**Comment by wbloszyk** [comment]
@jeroendk tomorrow I will add PR with ProfileBundle and drop SonataUserBundle requirement. First i need change some config and add docs.

**Comment by greg0ire** [comment]
> I am waiting for a stable 3.0 release for a while now.

I will talk to the team about this. Hopefully we can release one soon, even if that means 4.0 comes sooner than expected.

**Comment by salamichel** [comment]
@wbloszyk @greg0ire indeed from my side want to get ecommerce worked on Sf4.x \o/

**Comment by greg0ire** [comment]
I just released 3.0.0 so that you people have a nice place where to live. *That does not mean you will have to wait as much for 4.0*. Let's rename this issue!

**Comment by greg0ire** [comment]
In addition to the roadmap you are proposing, here is a project with extra tasks for 4.0: https://github.com/sonata-project/ecommerce/projects/1

**Comment by greg0ire** [comment]
Also @wbloszyk , please note that anything that is not a BC-break in your work can and should go to 3.x, not to master, so that everyone can benefit from it sooner. `master` should just be about dropping backwards-compatibility layers, and new things should go to 3.x.

**Comment by wbloszyk** [comment]
Ok. Thx for info. I just strat using git and github from 2-3month. I should add #614 to 2.3 branch?  2.3 have support for Sonatauserbundle 4.x where profile is missing. Of course i must make BC first.

**Comment by greg0ire** [comment]
No, 2.3 (or rather, 2x) branch is now for critical bugfixes. Please target 3.x instead.

**Comment by salamichel** [comment]
please add #623

**Comment by wbloszyk** [comment]
I add two RP, one for feature #627 and one for bug fixes #628 .

My next work:
1. Inject services to controllers (for extends AbstractController) - BC
1. remove public="true" from service

What do you think about it? Mybe have some more important things to do? @salamichel @greg0ire @jeroendk

**Comment by greg0ire** [comment]
Here are some ideas: https://github.com/sonata-project/dev-kit/issues/216 (e-commerce is not listed on that page but you get the idea)

**Comment by wbloszyk** [comment]
I update first message.
@greg0ire @salamichel @jeroendk @rande 
What du you think about it?

**Comment by salamichel** [comment]
@wbloszyk great i'm working one productCollection  navigation correct  #618. please add this on the roadmap

**Comment by wbloszyk** [comment]
@salamichel ecommerce 3.2.0 can be release after #627 and #631? I need this PR in sandbox.

@greg0ire @salamichel @jeroendk @slince @core23 
I will done work on stable sandbox 3.0 in this 2019 year, mybe even before christmas.

**Comment by VincentLanglet** [comment]
This bundle is abandoned
